### ISSUE TITLE
Decommission speakers.greensoftware.foundation & redirect

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/speakers#80]
Hi @osamajandali 

Please could we now decommission https://speakers.greensoftware.foundation/ and redirect to https://champions.greensoftware.foundation.

Once done we can archive this repo.

**Comment by osamajandali** [comment]
@jawache we don't have anymore page rules in cloudflare left, shall we buy more?


![Image](https://github.com/Green-Software-Foundation/speakers/assets/13832392/d17a8262-1be6-4aad-972b-ca2d4ccec230)

or shall I do client side redirect here? knowing the following disadvantages 


![Image](https://github.com/Green-Software-Foundation/speakers/assets/13832392/9fe6ef75-f23b-4f41-b24a-2e4c25ed58a2)

**Comment by jawache** [comment]
Happy to buy more, work with @seanmcilroy29 to arrange!

**Comment by adamj89** [comment]
@osamajandali how much do the redirects cost? Can you prepare some costs for @seanmcilroy29?

**Comment by osamajandali** [comment]
It's 1$/redirect but you only can buy 5-10-15,etc

**Comment by adamj89** [comment]
@seanmcilroy29 can you help with this please? We need to close down the old Speakers site and I'm not sure what action I can take from my side.

**Comment by jawache** [comment]
@osamajandali please can you take some screenshots and make it very clear what and how to buy what your looking for. Please add to this ticket and send an email also cc'ing me

**Comment by jawache** [comment]
Please provide the URL he should click, plus clear instructions as to the button.

**Comment by zanete** [comment]
@osamajandali can you please share the exact URL that sean should be visiting to pay for these.

**Comment by osamajandali** [comment]
@seanmcilroy29 here you are: https://dash.cloudflare.com/4be541059aa5dd4e1eeba3fce8af8a6e/greensoftware.foundation/rules
Please buy as many as you could as we do redirects a lot
cc: @zanete

**Comment by seanmcilroy29** [comment]
@osamajandali - I've updated the page rules to 20. Do you think this will be enough?

**Comment by osamajandali** [comment]
@seanmcilroy29 Thank you! this is enough yes

**Comment by osamajandali** [comment]
Done! Would take around a day to be deployed everywhere
@adamj89 I think we need to archive the repo by now

**Comment by jawache** [comment]
FYI @osamajandali when I go to speakers it still doesn't redirect 😜

**Comment by osamajandali** [comment]
@jawache Fixed
